name: SurvivalEvent
version: ${project.version}
main: xyz.masa3mc.survivalevent.SurvivalEvent
api-version: 1.17
depend:
  - WorldGuardEvents

commands:
  event:
    usage: /event
    description: for survival server event
