regions:
  - 8ma8
  - 8ma8_dai2
  - falled_can_farm
  - pyramid
  - pokemura
  - yuzu_skytower
  - icex_dai2
  - aniline_house
  - youmoukyaha
  - hyuga_shrine
  - flower_bridge
  - imatake_ic
  - centre_station
  - brendon
  - yuzumochi_airport
  - 8ma8_shintsu_sta_home
  - 8ma8_chiriyadai_sta_home
  - 8ma8_laputa
  - 8ma8_nishinouen_sta_home
  - new_spawn